services:
  themes:
    image: epam/ai-dial-chat-themes:0.6.0
    ports:
      - "3001:8080"
    networks:
      - dial-network
  chat:
    ports:
      - "3000:3000"
    image: epam/ai-dial-chat:0.17.0
    depends_on:
      - themes
      - core
    environment:
      NEXTAUTH_SECRET: "secret"
      THEMES_CONFIG_HOST: "http://themes:8080"
      DIAL_API_HOST: "http://core:8080"
      DIAL_API_KEY: "dial_api_key"
      ENABLED_FEATURES: "conversations-section,prompts-section,top-settings,top-clear-conversation,top-chat-info,top-chat-model-settings,empty-chat-settings,header,footer,request-api-key,report-an-issue,likes,input-files,attachments-manager"
      KEEP_ALIVE_TIMEOUT: ${CHAT_KEEP_ALIVE_TIMEOUT}
    networks:
      - dial-network
  redis:
    image: redis:7.2.4-alpine3.19
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 2000mb
      --maxmemory-policy volatile-lfu
      --save ""
      --appendonly no
      --loglevel warning
    mem_limit: 2200M
    networks:
      - dial-network
  core:
    user: ${UID:-root}
    ports:
      - "8080:8080"
    image: epam/ai-dial-core:0.16.0
    environment:
      'AIDIAL_SETTINGS': '/opt/settings/settings.json'
      'JAVA_OPTS': '-Dgflog.config=/opt/settings/gflog.xml'
      'LOG_DIR': '/app/log'
      'STORAGE_DIR': '/app/data'
      'aidial.config.files': '["/opt/config/config.json"]'
      'aidial.storage.overrides': '{ "jclouds.filesystem.basedir": "data" }'
      'aidial.redis.singleServerConfig.address': 'redis://redis:6379'
    depends_on:
      - redis
    volumes:
      - ./settings:/opt/settings
      - ./core:/opt/config
      - ./core-logs/:/app/log
      - ./core-data/:/app/data
    networks:
      - dial-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  adapter-openai:
    image: epam/ai-dial-adapter-openai:0.14.0
    environment:
      WEB_CONCURRENCY: "3"
      DIAL_URL: "http://core:8080"
      MODEL_ALIASES: '{"smollm2":"gpt-4", "llama3.2":"gpt-4o"}'
    networks:
      - dial-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm-proxy
    ports:
      - "4000:4000"
    volumes:
      - ./litellm/litellm-config.yaml:/app/config.yaml  
    environment:
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
    command: >
      --config /app/config.yaml --detailed_debug
    networks:
      - dial-network

  my-smart-app:
    build: ./my-smart-app
    environment:
      # 'MODEL': "llama3.2"
      # 'AZURE_ENDPOINT': "http://core:8080"
      # 'OPENAI_API_KEY': "dial_api_key"
      'AZURE_ENDPOINT': "https://ai-proxy.lab.epam.com"
      'MODEL': "gpt-4o-2024-05-13"
      'OPENAI_API_KEY': ${DIAL_API_KEY}
    networks:
      - dial-network

networks:
  dial-network:
    driver: bridge